export type MarketplaceSoftware = {
  id: string
  name: string
  logo: string
  logoBg: string
  tagline: string
  category: "Collaboration" | "Productivity" | "Cloud IT" | "AI/ML" | "Security" | "Development" | "Creative" | "Analytics" | "Utilities"
  priceLabel: string
  priceValue: number
  origin: string
  originFlag: string
  features: { icon: "shield" | "zap" | "cloud" | "users" | "lock" | "cpu" | "bar-chart" | "layers" | "globe" | "code" | "palette" | "message-circle" | "database" | "refresh-cw" | "eye"; label: string }[]
  rating: number
  reviews: number
  trending?: boolean
  featured?: boolean
}

export type MarketTrend = {
  id: string
  fromTool: string
  toTool: string
  percentage: number
  direction: "up" | "down"
  description: string
  timeframe: string
}

export const marketplaceSoftware: MarketplaceSoftware[] = [
  {
    id: "1",
    name: "Linear",
    logo: "LN",
    logoBg: "bg-chart-5",
    tagline: "Modern issue tracking built for speed",
    category: "Development",
    priceLabel: "Starting at $8/user/mo",
    priceValue: 8,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "zap", label: "Blazing fast UI" },
      { icon: "refresh-cw", label: "Automated workflows" },
      { icon: "code", label: "GitHub sync" },
    ],
    rating: 4.8,
    reviews: 1240,
    trending: true,
    featured: true,
  },
  {
    id: "2",
    name: "Notion",
    logo: "NO",
    logoBg: "bg-foreground",
    tagline: "All-in-one workspace for docs & wikis",
    category: "Productivity",
    priceLabel: "Starting at $10/user/mo",
    priceValue: 10,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "layers", label: "Flexible databases" },
      { icon: "users", label: "Real-time collab" },
      { icon: "globe", label: "Public sharing" },
    ],
    rating: 4.5,
    reviews: 3420,
    featured: true,
  },
  {
    id: "3",
    name: "Figma",
    logo: "FG",
    logoBg: "bg-chart-4",
    tagline: "Collaborative design tool for teams",
    category: "Creative",
    priceLabel: "Starting at $15/editor/mo",
    priceValue: 15,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "palette", label: "Vector editing" },
      { icon: "users", label: "Multiplayer design" },
      { icon: "code", label: "Dev mode" },
    ],
    rating: 4.9,
    reviews: 2890,
    trending: true,
    featured: true,
  },
  {
    id: "4",
    name: "Grafana Cloud",
    logo: "GC",
    logoBg: "bg-chart-3",
    tagline: "Open-source observability platform",
    category: "Analytics",
    priceLabel: "Starting at $19/mo",
    priceValue: 19,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "bar-chart", label: "Custom dashboards" },
      { icon: "eye", label: "Alerting & on-call" },
      { icon: "database", label: "Logs & traces" },
    ],
    rating: 4.3,
    reviews: 870,
  },
  {
    id: "5",
    name: "1Password",
    logo: "1P",
    logoBg: "bg-primary",
    tagline: "Enterprise password management",
    category: "Security",
    priceLabel: "Starting at $7.99/user/mo",
    priceValue: 7.99,
    origin: "Canada",
    originFlag: "CA",
    features: [
      { icon: "lock", label: "Zero-knowledge" },
      { icon: "shield", label: "SSO integration" },
      { icon: "users", label: "Team vaults" },
    ],
    rating: 4.7,
    reviews: 2100,
    featured: true,
  },
  {
    id: "6",
    name: "Miro",
    logo: "MR",
    logoBg: "bg-chart-3",
    tagline: "Visual collaboration whiteboard",
    category: "Collaboration",
    priceLabel: "Starting at $10/user/mo",
    priceValue: 10,
    origin: "Netherlands",
    originFlag: "NL",
    features: [
      { icon: "layers", label: "Infinite canvas" },
      { icon: "users", label: "Workshop tools" },
      { icon: "globe", label: "100+ integrations" },
    ],
    rating: 4.4,
    reviews: 1560,
  },
  {
    id: "7",
    name: "Vercel",
    logo: "VC",
    logoBg: "bg-foreground",
    tagline: "Frontend cloud for web deployment",
    category: "Cloud IT",
    priceLabel: "Starting at $20/user/mo",
    priceValue: 20,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "zap", label: "Instant deploys" },
      { icon: "globe", label: "Edge network" },
      { icon: "code", label: "Framework agnostic" },
    ],
    rating: 4.7,
    reviews: 1890,
    trending: true,
    featured: true,
  },
  {
    id: "8",
    name: "Anthropic Claude",
    logo: "AN",
    logoBg: "bg-chart-5",
    tagline: "Enterprise AI assistant & API",
    category: "AI/ML",
    priceLabel: "Starting at $25/mo",
    priceValue: 25,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "cpu", label: "200K context" },
      { icon: "shield", label: "Enterprise safety" },
      { icon: "code", label: "API access" },
    ],
    rating: 4.6,
    reviews: 980,
    trending: true,
    featured: true,
  },
  {
    id: "9",
    name: "SAP Concur",
    logo: "SP",
    logoBg: "bg-chart-2",
    tagline: "Travel & expense management",
    category: "Utilities",
    priceLabel: "Starting at $9/report",
    priceValue: 9,
    origin: "Germany",
    originFlag: "DE",
    features: [
      { icon: "bar-chart", label: "Expense reports" },
      { icon: "globe", label: "Travel booking" },
      { icon: "shield", label: "Policy compliance" },
    ],
    rating: 3.8,
    reviews: 640,
  },
  {
    id: "10",
    name: "Cloudflare",
    logo: "CF",
    logoBg: "bg-chart-3",
    tagline: "Global network & security platform",
    category: "Security",
    priceLabel: "Starting at $25/mo",
    priceValue: 25,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "shield", label: "DDoS protection" },
      { icon: "zap", label: "CDN & caching" },
      { icon: "lock", label: "Zero trust" },
    ],
    rating: 4.5,
    reviews: 2340,
    featured: true,
  },
  {
    id: "11",
    name: "Atlassian Jira",
    logo: "JR",
    logoBg: "bg-primary",
    tagline: "Project & issue tracking at scale",
    category: "Development",
    priceLabel: "Starting at $8.15/user/mo",
    priceValue: 8.15,
    origin: "Australia",
    originFlag: "AU",
    features: [
      { icon: "layers", label: "Scrum & kanban" },
      { icon: "bar-chart", label: "Advanced reports" },
      { icon: "globe", label: "3000+ add-ons" },
    ],
    rating: 3.4,
    reviews: 4200,
  },
  {
    id: "12",
    name: "WeTransfer",
    logo: "WT",
    logoBg: "bg-chart-5",
    tagline: "Simple, beautiful file sharing",
    category: "Utilities",
    priceLabel: "Starting at $10/mo",
    priceValue: 10,
    origin: "Netherlands",
    originFlag: "NL",
    features: [
      { icon: "cloud", label: "200GB transfers" },
      { icon: "lock", label: "Password protect" },
      { icon: "palette", label: "Custom branding" },
    ],
    rating: 4.2,
    reviews: 1120,
  },
  {
    id: "13",
    name: "Snowflake",
    logo: "SF",
    logoBg: "bg-chart-1",
    tagline: "Cloud data platform for analytics",
    category: "AI/ML",
    priceLabel: "Starting at $2/credit",
    priceValue: 40,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "database", label: "Data warehouse" },
      { icon: "zap", label: "Auto-scaling" },
      { icon: "shield", label: "Governance" },
    ],
    rating: 4.4,
    reviews: 1650,
  },
  {
    id: "14",
    name: "Intercom",
    logo: "IC",
    logoBg: "bg-chart-1",
    tagline: "AI-first customer service platform",
    category: "Productivity",
    priceLabel: "Starting at $39/seat/mo",
    priceValue: 39,
    origin: "Ireland",
    originFlag: "IE",
    features: [
      { icon: "message-circle", label: "AI chatbot" },
      { icon: "users", label: "Help center" },
      { icon: "bar-chart", label: "Customer data" },
    ],
    rating: 4.3,
    reviews: 1340,
  },
  {
    id: "15",
    name: "Alibaba Cloud",
    logo: "AL",
    logoBg: "bg-chart-3",
    tagline: "Cloud computing & intelligence",
    category: "Cloud IT",
    priceLabel: "Starting at $0.02/hr",
    priceValue: 15,
    origin: "China",
    originFlag: "CN",
    features: [
      { icon: "cloud", label: "Elastic compute" },
      { icon: "database", label: "Managed databases" },
      { icon: "globe", label: "Global regions" },
    ],
    rating: 4.0,
    reviews: 780,
  },
  {
    id: "16",
    name: "HubSpot",
    logo: "HS",
    logoBg: "bg-chart-3",
    tagline: "CRM, marketing & sales platform",
    category: "Analytics",
    priceLabel: "Starting at $20/seat/mo",
    priceValue: 20,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "users", label: "Contact management" },
      { icon: "bar-chart", label: "Marketing automation" },
      { icon: "message-circle", label: "Sales pipeline" },
    ],
    rating: 4.4,
    reviews: 3560,
    featured: true,
  },
  {
    id: "17",
    name: "Stripe",
    logo: "ST",
    logoBg: "bg-chart-5",
    tagline: "Payment infrastructure for the internet",
    category: "Utilities",
    priceLabel: "Starting at 2.9% + $0.30",
    priceValue: 0,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "lock", label: "PCI compliance" },
      { icon: "globe", label: "135+ currencies" },
      { icon: "code", label: "Developer-first API" },
    ],
    rating: 4.8,
    reviews: 4100,
  },
  {
    id: "18",
    name: "Datadog",
    logo: "DD",
    logoBg: "bg-chart-5",
    tagline: "Monitoring & security for cloud apps",
    category: "Analytics",
    priceLabel: "Starting at $15/host/mo",
    priceValue: 15,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "eye", label: "APM & tracing" },
      { icon: "bar-chart", label: "Infrastructure metrics" },
      { icon: "shield", label: "SIEM security" },
    ],
    rating: 4.5,
    reviews: 2010,
  },
  {
    id: "19",
    name: "Slack",
    logo: "SL",
    logoBg: "bg-chart-4",
    tagline: "Business messaging & collaboration hub",
    category: "Collaboration",
    priceLabel: "Starting at $8.75/user/mo",
    priceValue: 8.75,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "message-circle", label: "Channels & DMs" },
      { icon: "zap", label: "Workflow builder" },
      { icon: "globe", label: "2400+ integrations" },
    ],
    rating: 4.5,
    reviews: 5200,
  },
  {
    id: "20",
    name: "GitHub",
    logo: "GH",
    logoBg: "bg-foreground",
    tagline: "Code hosting & DevOps platform",
    category: "Development",
    priceLabel: "Starting at $4/user/mo",
    priceValue: 4,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "code", label: "Code review & PRs" },
      { icon: "zap", label: "GitHub Actions CI/CD" },
      { icon: "shield", label: "Dependabot security" },
    ],
    rating: 4.7,
    reviews: 6800,
  },
  {
    id: "21",
    name: "Zoom",
    logo: "ZM",
    logoBg: "bg-chart-1",
    tagline: "Video conferencing & communications",
    category: "Collaboration",
    priceLabel: "Starting at $13.33/user/mo",
    priceValue: 13.33,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "users", label: "Up to 1000 participants" },
      { icon: "cloud", label: "Cloud recording" },
      { icon: "shield", label: "End-to-end encryption" },
    ],
    rating: 4.3,
    reviews: 4500,
  },
  {
    id: "22",
    name: "MongoDB Atlas",
    logo: "MG",
    logoBg: "bg-chart-2",
    tagline: "Multi-cloud developer data platform",
    category: "Cloud IT",
    priceLabel: "Starting at $0.10/GB",
    priceValue: 10,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "database", label: "Document database" },
      { icon: "globe", label: "Multi-cloud deploy" },
      { icon: "zap", label: "Real-time sync" },
    ],
    rating: 4.4,
    reviews: 1780,
  },
  {
    id: "23",
    name: "Canva",
    logo: "CV",
    logoBg: "bg-chart-1",
    tagline: "Visual design platform for everyone",
    category: "Creative",
    priceLabel: "Starting at $13/user/mo",
    priceValue: 13,
    origin: "Australia",
    originFlag: "AU",
    features: [
      { icon: "palette", label: "Template library" },
      { icon: "users", label: "Brand kit sharing" },
      { icon: "globe", label: "100+ formats" },
    ],
    rating: 4.6,
    reviews: 3900,
  },
  {
    id: "24",
    name: "Sentry",
    logo: "SN",
    logoBg: "bg-chart-4",
    tagline: "Error tracking & performance monitoring",
    category: "Development",
    priceLabel: "Starting at $26/mo",
    priceValue: 26,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "eye", label: "Error tracking" },
      { icon: "bar-chart", label: "Performance monitoring" },
      { icon: "code", label: "50+ SDK integrations" },
    ],
    rating: 4.5,
    reviews: 1600,
  },
  {
    id: "25",
    name: "AWS",
    logo: "AW",
    logoBg: "bg-chart-3",
    tagline: "Comprehensive cloud services platform",
    category: "Cloud IT",
    priceLabel: "Starting at $0.01/hr",
    priceValue: 7,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "cloud", label: "200+ services" },
      { icon: "globe", label: "30+ regions" },
      { icon: "shield", label: "Compliance certs" },
    ],
    rating: 4.6,
    reviews: 8900,
  },
  {
    id: "26",
    name: "Asana",
    logo: "AS",
    logoBg: "bg-chart-3",
    tagline: "Work management for modern teams",
    category: "Productivity",
    priceLabel: "Starting at $10.99/user/mo",
    priceValue: 10.99,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "layers", label: "Project timelines" },
      { icon: "zap", label: "Rules automation" },
      { icon: "bar-chart", label: "Portfolios & goals" },
    ],
    rating: 4.3,
    reviews: 2700,
  },
  {
    id: "27",
    name: "Okta",
    logo: "OK",
    logoBg: "bg-primary",
    tagline: "Identity & access management",
    category: "Security",
    priceLabel: "Starting at $2/user/mo",
    priceValue: 2,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "lock", label: "Single sign-on" },
      { icon: "shield", label: "Adaptive MFA" },
      { icon: "users", label: "Lifecycle mgmt" },
    ],
    rating: 4.4,
    reviews: 1900,
  },
  {
    id: "28",
    name: "Airtable",
    logo: "AT",
    logoBg: "bg-chart-1",
    tagline: "Connected apps platform for teams",
    category: "Productivity",
    priceLabel: "Starting at $20/user/mo",
    priceValue: 20,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "database", label: "Relational data" },
      { icon: "zap", label: "Automations" },
      { icon: "layers", label: "Interface designer" },
    ],
    rating: 4.4,
    reviews: 2300,
  },
  {
    id: "29",
    name: "Twilio",
    logo: "TW",
    logoBg: "bg-chart-4",
    tagline: "Cloud communications APIs",
    category: "Utilities",
    priceLabel: "Starting at $0.0079/msg",
    priceValue: 0,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "message-circle", label: "SMS & voice APIs" },
      { icon: "code", label: "Developer SDKs" },
      { icon: "globe", label: "180+ countries" },
    ],
    rating: 4.2,
    reviews: 1450,
  },
  {
    id: "30",
    name: "Loom",
    logo: "LM",
    logoBg: "bg-chart-5",
    tagline: "Async video messaging for teams",
    category: "Collaboration",
    priceLabel: "Starting at $12.50/user/mo",
    priceValue: 12.50,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "eye", label: "Screen recording" },
      { icon: "zap", label: "AI transcription" },
      { icon: "users", label: "Team library" },
    ],
    rating: 4.6,
    reviews: 1800,
  },
  {
    id: "31",
    name: "PagerDuty",
    logo: "PD",
    logoBg: "bg-chart-2",
    tagline: "Digital operations management",
    category: "Utilities",
    priceLabel: "Starting at $21/user/mo",
    priceValue: 21,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "zap", label: "Incident response" },
      { icon: "bar-chart", label: "Service analytics" },
      { icon: "refresh-cw", label: "On-call scheduling" },
    ],
    rating: 4.3,
    reviews: 920,
  },
  {
    id: "32",
    name: "Webflow",
    logo: "WF",
    logoBg: "bg-primary",
    tagline: "Visual web development platform",
    category: "Creative",
    priceLabel: "Starting at $14/mo",
    priceValue: 14,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "palette", label: "Visual builder" },
      { icon: "code", label: "Clean code output" },
      { icon: "globe", label: "CMS & hosting" },
    ],
    rating: 4.5,
    reviews: 1340,
  },
  {
    id: "33",
    name: "Mixpanel",
    logo: "MX",
    logoBg: "bg-chart-5",
    tagline: "Product analytics that drive results",
    category: "Analytics",
    priceLabel: "Starting at $28/mo",
    priceValue: 28,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "bar-chart", label: "Funnel analysis" },
      { icon: "users", label: "User segmentation" },
      { icon: "eye", label: "Retention reports" },
    ],
    rating: 4.4,
    reviews: 1100,
  },
  {
    id: "34",
    name: "Postman",
    logo: "PM",
    logoBg: "bg-chart-3",
    tagline: "API platform for building & testing",
    category: "Development",
    priceLabel: "Starting at $14/user/mo",
    priceValue: 14,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "code", label: "API testing" },
      { icon: "layers", label: "Workspace collab" },
      { icon: "refresh-cw", label: "Mock servers" },
    ],
    rating: 4.5,
    reviews: 3200,
  },
  {
    id: "35",
    name: "Crowdstrike",
    logo: "CS",
    logoBg: "bg-chart-4",
    tagline: "Endpoint security & threat intelligence",
    category: "Security",
    priceLabel: "Starting at $8.99/device/mo",
    priceValue: 8.99,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "shield", label: "EDR protection" },
      { icon: "eye", label: "Threat hunting" },
      { icon: "cpu", label: "AI-powered detection" },
    ],
    rating: 4.6,
    reviews: 1750,
  },
  {
    id: "36",
    name: "Tableau",
    logo: "TB",
    logoBg: "bg-chart-1",
    tagline: "Business intelligence & data visualization",
    category: "Analytics",
    priceLabel: "Starting at $15/user/mo",
    priceValue: 15,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "bar-chart", label: "Interactive dashboards" },
      { icon: "database", label: "Data connectors" },
      { icon: "eye", label: "Visual analytics" },
    ],
    rating: 4.3,
    reviews: 2800,
  },
  {
    id: "37",
    name: "OpenAI",
    logo: "OA",
    logoBg: "bg-foreground",
    tagline: "Advanced AI models & API platform",
    category: "AI/ML",
    priceLabel: "Starting at $20/mo",
    priceValue: 20,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "cpu", label: "GPT models" },
      { icon: "code", label: "API & SDK access" },
      { icon: "shield", label: "Enterprise controls" },
    ],
    rating: 4.7,
    reviews: 5400,
    trending: true,
  },
  {
    id: "38",
    name: "Supabase",
    logo: "SB",
    logoBg: "bg-chart-2",
    tagline: "Open source Firebase alternative",
    category: "Development",
    priceLabel: "Starting at $25/mo",
    priceValue: 25,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "database", label: "Postgres database" },
      { icon: "lock", label: "Auth & RLS" },
      { icon: "zap", label: "Realtime subscriptions" },
    ],
    rating: 4.6,
    reviews: 1400,
    trending: true,
  },
  {
    id: "39",
    name: "Shopify",
    logo: "SH",
    logoBg: "bg-chart-2",
    tagline: "Commerce platform for businesses",
    category: "Utilities",
    priceLabel: "Starting at $39/mo",
    priceValue: 39,
    origin: "Canada",
    originFlag: "CA",
    features: [
      { icon: "globe", label: "Online storefront" },
      { icon: "bar-chart", label: "Sales analytics" },
      { icon: "layers", label: "App ecosystem" },
    ],
    rating: 4.4,
    reviews: 4800,
  },
  {
    id: "40",
    name: "ClickUp",
    logo: "CU",
    logoBg: "bg-chart-5",
    tagline: "Everything app for work management",
    category: "Productivity",
    priceLabel: "Starting at $7/user/mo",
    priceValue: 7,
    origin: "USA",
    originFlag: "US",
    features: [
      { icon: "layers", label: "Custom views" },
      { icon: "zap", label: "Automations" },
      { icon: "users", label: "Team spaces" },
    ],
    rating: 4.2,
    reviews: 2100,
  },
]

export const marketTrends: MarketTrend[] = [
  {
    id: "1",
    fromTool: "Jira",
    toTool: "Linear",
    percentage: 15,
    direction: "up",
    description: "15% of teams switching from Jira to Linear for faster workflows",
    timeframe: "This month",
  },
  {
    id: "2",
    fromTool: "Datadog",
    toTool: "Grafana Cloud",
    percentage: 12,
    direction: "up",
    description: "12% migrating to Grafana for open-source flexibility and lower costs",
    timeframe: "This quarter",
  },
  {
    id: "3",
    fromTool: "Zoom",
    toTool: "Google Meet",
    percentage: 22,
    direction: "up",
    description: "22% of orgs consolidating video into Google Workspace suite",
    timeframe: "Last 60 days",
  },
  {
    id: "4",
    fromTool: "Slack",
    toTool: "Microsoft Teams",
    percentage: 8,
    direction: "down",
    description: "8% shift detected, but Slack retention remains strong at 92%",
    timeframe: "This quarter",
  },
  {
    id: "5",
    fromTool: "OpenAI",
    toTool: "Anthropic Claude",
    percentage: 18,
    direction: "up",
    description: "18% of enterprise AI users adding Claude for long-context tasks",
    timeframe: "This month",
  },
]

export const allMarketplaceCategories = Array.from(
  new Set(marketplaceSoftware.map((s) => s.category))
).sort()

export const allOrigins = Array.from(
  new Set(marketplaceSoftware.map((s) => s.origin))
).sort()
